version: '3.8'

x-env:
  common:
    environment: &common-env
      ENVIRONMENT: 'development'

x-restarts:
  restart: &restarts on-failure

services:
  mongo:
    container_name: "${PROJECT}_mongo"
    image: mongo:3.6.3
    volumes:
      - './data/mongo:/data/db'
    logging:
      driver: none

  eqr-test-sdk:
    environment: *common-env
    restart: *restarts
    build:
      context: eqr-test-sdk
      dockerfile: Dockerfile.dev
    container_name: "${PROJECT}_eqr-test-sdk"
    image: "${PROJECT}/eqr-test-sdk:latest-dev"
    volumes:
      - './eqr-test-sdk:/usr/src/app'
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
