version: '3.8'

x-env:
  common:
    environment: &common-env
      ENVIRONMENT: 'development'

x-restarts:
  restart: &restarts on-failure

services:
  mongo:
    container_name: "${PROJECT}_mongo"
    image: mongo:3.6.3
    volumes:
      - './data/mongo:/data/db'
    logging:
      driver: none

  e2e-suite:
    environment: *common-env
    restart: *restarts
    build:
      context: e2e-suite
      dockerfile: Dockerfile.dev
    container_name: "${PROJECT}_e2e-suite"
    image: "${PROJECT}/e2e-suite:latest-dev"
    volumes:
      - './e2e-suite:/usr/src/app'
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
